### PR TITLE
grid formatter changes, abstract formatter class, backward-slash support

### PR DESCRIPTION
**Pull request by DarkSide666**
* backward slashes `\` are used in namespaces
* in theory forward slashes `/` shouldn't be used, but we should leave them here for compatibility reasons

### CODE REVIEW

**Comment by DarkSide666** [comment]
OK, I'll make some fixes in this pull request then. I'll let you know when it's ready for review.

**Comment by romaninsh** [comment]
ok, i guess we should add your fix for handling \\ , after all if they want to use backslashes, who are we to deny. 

It won't be in docs though.

**Comment by DarkSide666** [comment]
Yeah. Otherwise more issues will arise if we use __NAMESPACE__ in model->field->display() for example and definitely there are more. It's not just add() method which is involved.

**Comment by romaninsh** [comment]
yep... addField( 

so not sure if it should be part of testing.

**Pull request merged**
