### PR TITLE
Adds ADView controller

### PR DESCRIPTION
**Pull request by DarkSide666**
Adds ADView controller.
* more correct than AbstractView->modelRender() method
* also supports AD model field captions in templates
* treats different field types correctly

### CODE REVIEW

**Comment by romaninsh** [comment]
Note - I didn't see where it actually replaced modelRender method. Will have to test it.

**Comment by DarkSide666** [comment]
Usage - set this controller in your view:
```
class MyView extends View {
    public $default_controller = 'ADView';
    ...
```

Maybe it should better be implemented directly in AbstractView->modelRender() method instead of controller,but I thought that controller approach is a bit more elegant :)

**Comment by romaninsh** [comment]
that's what i thought - you have to set it manually. OK, no problem but would be nice if it works out of the box, just like regular ATK models.

**Comment by romaninsh** [comment]
Controller can be used, but should be invoked automatically.

**Pull request merged**
